# Generated by Django 4.0.6 on 2022-07-25 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_modpack_page_comment_delete_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='comment',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='page.comment'),
        ),
    ]
