# Generated by Django 4.0.6 on 2022-07-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0001_initial'),
        ('user', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='following_mod',
            field=models.ManyToManyField(blank=True, to='mod.mod'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
