# Generated by Django 4.0.6 on 2022-08-05 09:36

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_options_customuser_following_mod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or less, may contain only English letters, numbers, and . _ characters.', max_length=20, unique=True, validators=[user.utils.UsernameValidator()]),
        ),
    ]
