# Generated by Django 4.0.6 on 2022-07-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0002_download_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
