# Generated by Django 4.0.6 on 2022-07-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0004_alter_mod_category_alter_modversion_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='image',
            field=models.ImageField(blank=True, upload_to='MainModImages/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='modversion',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='ModFiles/%Y/%m/%d'),
        ),
    ]
