# Generated by Django 4.0.6 on 2022-08-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0005_mod_image_alter_modversion_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='slug',
            field=models.SlugField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod',
            name='image',
            field=models.ImageField(blank=True, upload_to='ModMainImages/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
