# Generated by Django 4.0.6 on 2022-08-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0006_mod_slug_alter_mod_image_alter_mod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modversion',
            name='slug',
            field=models.SlugField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
