# Generated by Django 4.0.6 on 2022-08-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0007_modversion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='GameImages/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ModMainImages/%Y/%m/%d'),
        ),
        migrations.AlterUniqueTogether(
            name='modversion',
            unique_together={('mod', 'version')},
        ),
        migrations.RemoveField(
            model_name='modversion',
            name='slug',
        ),
    ]
